### Change password
POST {{baseURL}}/session/recover/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpaGFwcEBvdXRsb29rLmNvbSIsImlhdCI6MTc1MjI4OTE2OCwiZXhwIjoxNzUyMjkyNzY4LCJzdWIiOiJlZjhjYjQ0YS00ZjdkLTQ4NWUtOTU3ZS04NWIzMDllYzE3NDgifQ.1Jw4pt9fd8F89oXLKm6yUcWvm8nZ5oyY5EGh67Fvd-E
Content-Type: application/json

{
  "password": "newPassword"
}